### ISSUE TITLE
simicLASSO_op inputs and arguments

### ISSUE THREAD

**Issue by bsierieb1** [jianhao2016/simicLASSO_git#4]
Hi,

I have several questions how to correctly specify the inputs and arguments of `simicLASSO_op()`.

My data set has 130 clusters and contains cells of 2 "phenotypes" - control and test.

1. `simicLASSO_op` help text says:
```
p2df: path to dataframe
            dataframe should be:
                    gene1, gene2, ..., genek, label
            cell1:  x,     x,   , ..., x,   , type1
            cell2:  x,     x,   , ..., x,   , type2
```
Do I understand correctly that "type1", "type2" etc does NOT refer to the cell type? Instead, these are cell "phenotypes", i.e. "control" and "test" in my case, right?

2. What exactly should `p2assignment` be in my case? The SimiC preprint says that "in cases with only two cell phenotypes (e.g., case vs control), the ordering is implicit." I am not sure I understand what it means. Should I just assign 0 to my "control" cells and 1 to the "test" cells?

3. `k_cluster` is simply the number of clusters, right? I am a little confused as to why only the total number (130 in my case) must be specified without actually providing the cell-by-cell cluster assignment.

4. What is `_NF`? It is not explained in the help text.

5. Any recommendations how to set the two `lambda` parameters? `lambda1` and `lambda2` arguments in the example notebook deviate considerably from the defaults. Is some sort of hyperparameter search required to do that?

Thank you!

**Comment by jianhao2016** [comment]
Hi bsierib1

1. If you are trying to find the difference dynamics between 'control' and 'test', then the labels should be phenotypes. By the end of the process, you will have two GRNs, and two set of regulon activity scores. From there you can group them by clusters and check the regulon dissimilarity or perform clusterings, etc
2. ```p2assignment``` is a list of cell labels in integers according to the pseudo temporal order. So in your case control group can be labeled as all `0`s, and test can be `1`. You can refer to #https://github.com/jianhao2016/SimiC/blob/master/example/test_data/test_assignment.txt for an example of 3 types. In the case of multiple phenotypes/time points. It can be values in `[0, N]` for each cell in their group. 
3. ` k_cluster` is not required if you have `p2assignment`. It was only use when the order is unknown. 
4. `_NF` is a normalization factor you can tune if the optimization process is unstable due to numerical issues. You can set to `100`. 
5. Yes, hyperparameter search is recommended. Based on prior knowledge, if the two types are relatively closer, then `\lambda_2` can be larger, otherwise smaller. And if you want the GRN to be sparser, then `\lambda_1` can be larger, vice versa. 

Bests,
Jianhao

**Comment by bsierieb1** [comment]
Fantastic, thanks, @jianhao2016
